# Generated by Django 5.1.2 on 2024-10-13 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='create_project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=1234)),
                ('project_discription', models.TextField()),
                ('git_hub_url', models.URLField()),
                ('live_url', models.URLField()),
            ],
        ),
    ]
